///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Users {
/*
{
  "gender": "여성",
  "name": "김바보",
  "smoke": "비흡연자",
  "weight": "52",
  "style": "귀여운",
  "sendlike": "id",
  "job": "유치원 교사",
  "heart": "id",
  "drink": "한병",
  "age": 25,
  "height": "167",
  "religion": "기독교"
}
*/

  String? gender;
  String? name;
  String? smoke;
  String? weight;
  String? style;
  String? sendlike;
  String? job;
  String? heart;
  String? drink;
  int? age;
  String? height;
  String? religion;

  Users({
    this.gender,
    this.name,
    this.smoke,
    this.weight,
    this.style,
    this.sendlike,
    this.job,
    this.heart,
    this.drink,
    this.age,
    this.height,
    this.religion,
  });
  Users.fromJson(Map<String, dynamic> json) {
    gender = json['gender']?.toString();
    name = json['name']?.toString();
    smoke = json['smoke']?.toString();
    weight = json['weight']?.toString();
    style = json['style']?.toString();
    sendlike = json['sendlike']?.toString();
    job = json['job']?.toString();
    heart = json['heart']?.toString();
    drink = json['drink']?.toString();
    age = json['age']?.toInt();
    height = json['height']?.toString();
    religion = json['religion']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['gender'] = gender;
    data['name'] = name;
    data['smoke'] = smoke;
    data['weight'] = weight;
    data['style'] = style;
    data['sendlike'] = sendlike;
    data['job'] = job;
    data['heart'] = heart;
    data['drink'] = drink;
    data['age'] = age;
    data['height'] = height;
    data['religion'] = religion;
    return data;
  }
}
