// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiibUkqHLtx_qwxyKwn4OWclc1CFYEsvQ',
    appId: '1:846343932547:web:ef675aa2d04991f9de69b6',
    messagingSenderId: '846343932547',
    projectId: 'fir-22-2e754',
    authDomain: 'fir-22-2e754.firebaseapp.com',
    storageBucket: 'fir-22-2e754.appspot.com',
    measurementId: 'G-22WT502L4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuPdNJfTx33CHN_xdN6PzWYe-adnOtroM',
    appId: '1:846343932547:android:fe34046938976230de69b6',
    messagingSenderId: '846343932547',
    projectId: 'fir-22-2e754',
    storageBucket: 'fir-22-2e754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZR7gB3gMbLPYfNdsCddQocXaffhVD5rU',
    appId: '1:846343932547:ios:da15795d2671bab6de69b6',
    messagingSenderId: '846343932547',
    projectId: 'fir-22-2e754',
    storageBucket: 'fir-22-2e754.appspot.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZR7gB3gMbLPYfNdsCddQocXaffhVD5rU',
    appId: '1:846343932547:ios:f713256bbfccbb01de69b6',
    messagingSenderId: '846343932547',
    projectId: 'fir-22-2e754',
    storageBucket: 'fir-22-2e754.appspot.com',
    iosBundleId: 'com.example.firebaseflutter.RunnerTests',
  );
}
