// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCLlnrIOaQuHdUqXnA6-efWr90pEQNS6Q',
    appId: '1:462034581420:web:bdfd4da7cc7b28f5c26c09',
    messagingSenderId: '462034581420',
    projectId: 'flutter-8283b',
    authDomain: 'flutter-8283b.firebaseapp.com',
    storageBucket: 'flutter-8283b.appspot.com',
    measurementId: 'G-GM84KC2JCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM1KeWMkxOx85iFDnYFjv52zRkkI4BGO0',
    appId: '1:462034581420:android:224db5930c6072e1c26c09',
    messagingSenderId: '462034581420',
    projectId: 'flutter-8283b',
    storageBucket: 'flutter-8283b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXP8_LOqFmF9Z-4qgeWo2D5MWtqcfm_qA',
    appId: '1:462034581420:ios:1e30f812ac8290e7c26c09',
    messagingSenderId: '462034581420',
    projectId: 'flutter-8283b',
    storageBucket: 'flutter-8283b.appspot.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXP8_LOqFmF9Z-4qgeWo2D5MWtqcfm_qA',
    appId: '1:462034581420:ios:1f9121221c4b1a04c26c09',
    messagingSenderId: '462034581420',
    projectId: 'flutter-8283b',
    storageBucket: 'flutter-8283b.appspot.com',
    iosBundleId: 'com.example.firebaseflutter.RunnerTests',
  );
}
